name: Build per subdir (Cloudflare Pages)

on:
  push:
    branches: [ main ]
    paths:
      - 'kalkulator-pinjaman/**'
      - 'kalender-nasional/**'

jobs:
  kalkulator:
    if: contains(join(github.event.commits.*.modified, ' '), 'kalkulator-pinjaman/') ||
        contains(join(github.event.commits.*.added, ' '), 'kalkulator-pinjaman/') ||
        contains(join(github.event.commits.*.removed, ' '), 'kalkulator-pinjaman/')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy kalkulator-pinjaman
        run: curl -X POST "${{ secrets.CF_PAGES_HOOK_KALKULATOR }}"

  kalender:
    if: contains(join(github.event.commits.*.modified, ' '), 'kalender-nasional/') ||
        contains(join(github.event.commits.*.added, ' '), 'kalender-nasional/') ||
        contains(join(github.event.commits.*.removed, ' '), 'kalender-nasional/')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy kalender-nasional
        run: curl -X POST "${{ secrets.CF_PAGES_HOOK_KALENDER }}"
